language: python
sudo: false

python:
  - "2.7"

virtualenv:
  system_site_packages: false

before_install:
  # For tests running hg command
  # set up username
  - echo '[ui]' > ~/.hgrc
  - echo 'username = anybox-test' >> ~/.hgrc


install:
  - pip install coveralls
  - pip install flake8
  - pip install -e .[test]

script:
  - python setup.py flake8
  - python setup.py nosetests
  # install sphinx only after running tests to avoid failing tests
  - pip install sphinx; python setup.py build_sphinx

after_script:
  # Dump version of all installed packages
  - echo 'Versions of all installed packages';  echo '=================================='; pip freeze -l anybox.recipe.odoo

after_success:
  - coveralls 
